# Generated by Django 3.0.7 on 2020-06-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Categorey'),
        ),
    ]
