# Generated by Django 3.0.7 on 2020-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_categorey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
