# Generated by Django 3.0.7 on 2020-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='service_product',
        ),
    ]
