# Generated by Django 3.0.7 on 2020-06-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200619_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='email',
        ),
    ]
