# Generated by Django 3.0.7 on 2020-06-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200619_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categorey'),
        ),
    ]
