# Generated by Django 3.0.7 on 2020-06-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_shippingaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone',
        ),
    ]
