# Generated by Django 3.0.7 on 2020-06-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200626_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
    ]
